### ISSUE TITLE
Produkt side

### ISSUE THREAD

**Issue by rediche** [rediche/shop-theme#3]
Implementer produkt side

* Skal integreres med WooCommerce

**Comment by rediche** [comment]
Denne mangler stadig SKU (Varenr.) på dens template. Men det er ikke særligt vigtigt lige nu. Kan evt. være det skal være sin egen case.

**Comment by afrotheniceguy** [comment]
Tekststørrelse på overskriften må gerne gøres mindre

**Comment by rediche** [comment]
SKU og tekststørrelse er rettet. Flytter dene case til done. Andet til produktsiden bør laves som individuelle cases.
