### ISSUE TITLE
Page builder - p elementer får top margin.

### ISSUE THREAD

**Issue by afrotheniceguy** [rediche/shop-theme#68]
P får margin-top, hvilket driller i page builderen. Kan dette nulstilles ved brug af page builder?
I hvert fald så "first-child" ikke får denne?

http://hobby.uniktdesign.dk/butik/

http://hobby.uniktdesign.dk/kundeservice/

**Comment by rediche** [comment]
First child på p-elementer lyder som en god idé. Prøv det af, og tjek så sitet igennem i tilfældet af, at det har ødelagt noget. 

Husk at lav en ny branch fra master. 

Typebase.css er hvor jeg ville indsætte den selector :)

**Comment by rediche** [comment]
Endte med, at ændre alle `<p>`'s til, at have margin-bottom per default i stedet for margin-top.
